### ISSUE TITLE
Gno.land Developer Call Agenda {09.08.2023}_ #11

### ISSUE THREAD

**Issue by michelleellen** [gnolang/meetings#25]
![image](https://github.com/gnolang/meetings/assets/117160070/53bcf10d-336a-4ed5-9455-b3383208ee02)

### Description
Join Gnolang's core tech team and partners for the bi-weekly developer call, a regular sync with Gnolang developers working on the technology and community members interested in the engineering and development discussions. You can find the proposed agenda below, if you have additional technical points to discuss, please add them to this issue.

Date: August 9th at 5pm CEST
Dial in details shared with core contributors (if you're interested in joining, and actively contributing to the code base, please reach out).

You can add the Developer Call to your calendar [here](https://calendar.google.com/calendar/u/0?cid=Y18xZTVlY2M4NWNhYzY3ZDBiZGE5ZDI3YWRmZjRlOTBiZDMyMjY4ZjI1YTYyMmExZGViODQyMjEwMzllODc4OWEyQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20).

### Agenda
**Gno Contributor Updates**

- [x] Teritori
- [x] Onbloc
- [x] Welcome Berty ❤️
- [ ] GnoIDE
- [ ] 

**Gno Team Topics**

Follow ups from last time, any short updates?
Do we have an issue to discuss reflection?
Alternative to reflection, introspection [issue 970](https://github.com/gnolang/gno/issues/971) (@peter7891)

**New topics for updates:
Gnopher Holes:**

- [ ] Module VS Pkg VS Path VS Dir VS SubPkg VS SubModule VS SubDir VS SubPath [issue 1024](https://github.com/gnolang/gno/issues/1024) (@harry-hov @moul @jaekwon)
- [x] Unexpected panic error when fetching height [issue 1037](https://github.com/gnolang/gno/issues/1037)(@gfanton)
- [ ] 

**Open issue discussions:**

- [x] Discussion: META 'gno' CLI [issue 1017](https://github.com/gnolang/gno/issues/1017)(@moul @mvertes)
- [x]  Discussion language: Extending constant behavior [issue 919](https://github.com/gnolang/gno/issues/919) (@peter7891 )
- [ ]  Discussion banker module [issue 986](https://github.com/gnolang/gno/issues/986) (@thehowl) maybe related by grc20 and dynamic call closure https://github.com/gnolang/gno/issues/986 (@moul )
- [ ]  Discussion: Merkle airdrop [issue 906](https://github.com/gnolang/gno/pull/906)(@albttx)
- [x]  Discussion: Error handling in the send transaction function of [issue 46](https://github.com/gnolang/tm2-js-client/issues/46) @zivkovicmilos @jaekwon -
- [ ]  Discussion: another improved error handling proposal [issue 1018](https://github.com/gnolang/gno/issues/1018) part of go proposals (@peter7891 @mvertes)
- [ ]  Discussion on the draft allow args on main run [issue 982](https://github.com/gnolang/gno/pull/982) (@ajnavarro )
- [ ]  Discussion on Contributors DAO --[issue 872](https://github.com/gnolang/gno/issues/872) (@moul 
- [ ]  Merged: Benchmark and performance metrics issue [881](https://github.com/gnolang/gno/pull/881) and [live](https://ajnavarro.com/gno-benchmarks/) @ajnavarro
- [ ] 

Follow up/actions:

- [ ] @thehowl to open a META issue regarding reflection

**Comment by jefft0** [comment]
Topic: What is the intended way to use the code as a "library"? Berty is writing a mobile app to directly interact with the blockchain (not using the CLI). We need utility functions like [signAndBroadcast](https://github.com/gnolang/gno/blob/a612e5715b8761eb4412e1433501b00f47713585/tm2/pkg/crypto/keys/client/addpkg.go#L138) which is private. Do we just copy this code or what?
