### ISSUE TITLE
Gno.land Developer Call - 5 {03.05.2023} 

### ISSUE THREAD

**Issue by michelleellen** [gnolang/meetings#8]
![image](https://user-images.githubusercontent.com/117160070/235721406-ae52908d-1d54-4c58-86b6-6b70a1e880b6.png)

### Description

Join Gnolang's core tech team and partners for the monthly developer call, a regular sync with Gnolang developers working on the technology and community members interested in the engineering and development discussions. You can find the proposed agenda below, if you have additional technical points to discuss, please add them to this issue.

Date: May 3rd at 5pm CET
Dial in details shared with core contributors (if you're interested in joining, and actively contributing to the code base, please reach out) and live stream on Gno.land [YouTube](https://www.youtube.com/@_gnoland/featured)

You can add the Developer Call to your calendar [here](https://calendar.google.com/calendar/u/0?cid=Y18xZTVlY2M4NWNhYzY3ZDBiZGE5ZDI3YWRmZjRlOTBiZDMyMjY4ZjI1YTYyMmExZGViODQyMjEwMzllODc4OWEyQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20).

Tentative agenda 
- [x]  Updates from the Gno core tech and core contributors (Everyone 🙏)
**onbloc** 
Adena upgrade
Swap 
**Sage**
**Zack**
[Microblog
](https://github.com/schollz/gno/tree/microblog)
-  [x] [Benchmarking](https://github.com/gnolang/gno/issues/689) (Petar/Morgan)
- [ ] CLI refactor [issue 731](https://github.com/gnolang/gno/issues/731#issuecomment-1508009022) (Manfred)
- [x] Gno js SDK update and discussion - [repo](https://github.com/gnolang/gno-js-sdk) (Milos)
- [x] Gno IDE updates (ilker)
- [ ] Garbage collector updates (Petar)
- [ ] IBC updates (Jae)
- [ ] Discussion on handling total supply and balance ([issue](https://github.com/gnolang/gno/issues/741#issuecomment-1508147839))
- [ ] Protocol to support contract contract interaction continued discussion ([issue](https://github.com/gnolang/gno/pull/473)) and handling grc20 treasury (linked to the Merkle airdrop) management 
- [ ] - Best joke from Petar 😁 - always save the best for last

@gnolang/core-contributors @gnolang/tech-staff
